run:
  skip-dirs:
    - scripts
    - vendor
  timeout: 3m

linters:
  enable:
    - deadcode
    - dupl
    - errcheck
    - funlen
    - gocyclo
    - goconst
    - gofmt
    - gosimple
    - govet
    - goimports
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - vet
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - godot
    - godox
    - goerr113
    - gofumpt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    ignore: bytes:.*,io:Close|Write

  lll:
    line-length: 160

  stylecheck:
    pkg_name: false
    camel_name: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - stylecheck
        - goerr113
        - lll
        - funlen
