name: Test Go

on:
  workflow_call:
    outputs:
      tag:
        description: "The next semantic version tag based on commit messages."
        value: ${{ jobs.calculate-tag.outputs.tag }}

jobs:
  calculate-tag:
    name: "Calculate Semver Tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Calculate the next SemVer tag
        id: tag
        run: |
          TAG="$(make calculate-next-semver)"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Check the next tag
        run: "echo 'This change will result in version: ${{ steps.tag.outputs.tag }}'"
    outputs:
      tag: "${{ steps.tag.outputs.tag }}"

  test:
    name: "Run Go tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setup Go
        uses:  actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: 'go.mod'
      - name: Run Go tests
        run: make test

  lint-go:
    name: "Lint Go"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setup Go
        uses:  actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: 'go.mod'
      - name: Lint
        run: make lint
